### ISSUE TITLE
Crash when editing NAT rules

### ISSUE THREAD

**Issue by ghost** [UNINETT/fwbuilder#5]
fwbuilder crashes on me whenever I try to update my NAT rules, this happens on both mac and Windows binary.

I'm could have sworn I already opened an issue for this but I can't find it :)

**Comment by ghost** [comment]
I found my bug report, it's under sirius/fwbuilder not here :)

Sorry!

**Comment by sirius** [comment]
@stevec99 No problem :smile: Could you give some more details about your crash? Which version of fwbuilder are you running?

**Comment by ghost** [comment]
5.3.6

I have an outbound NAT rule for example, if I try an add a new network object to the source, either by dragging and dropping or by copying and pasting, fwbuilder crashes and dies.

It's not rule specific, all NAT rules do the same thing.

I normally use MacOS version, I did install WIndows version on a VM, this has the same behaviour.

This is reproducible everytime.

**Comment by ghost** [comment]
Same thing happens when I try and edit any part if the NAT rules, source, destination, services etc.

Also creating a completely new firewall in a new 'project', same behaviour.

Example, open fwbuilder, create new firewall (iptables defaults) add a NAT rule, add http to one of the services column, crash.

**Comment by sirius** [comment]
Thanks, I'll do some debugging.

**Comment by bizonix** [comment]
I have the same issue!
MacOS version of fwbuilder v5.3.6-1-gf09bdd1-dev
Saved crash report for fwbuilder[68097] version 0 to https://gist.github.com/anonymous/f33153793d111b9f4f7c

**Comment by sirius** [comment]
@bizonix Thanks. I assume it's connected to modifications to the undo/redo system, which again is connected to the dummy functionality I added. I'll keep you updated when I have a fix.

**Comment by ghost** [comment]
Hmm, is there any way of temporarily getting round this, I really need to add some NAT rules :)

**Comment by sirius** [comment]
@stevec99 You're lucky - I've begun in my summer job today: contributing to fwbuilder. I'll do my best to test my patch and provide new binaries today.

**Comment by sirius** [comment]
@stevec99 @bizonix @pmoetteli Can you confirm that the small fix in d79acf40997d75f33513240543fd4d5862a4593b fixes your problem?

This should fix https://github.com/sirius/fwbuilder/issues/3 too.

**Comment by pmoetteli** [comment]
Hello,

> Am 23.06.2015 um 10:47 schrieb Sirius Bakke notifications@github.com:
> 
> @stevec99 @bizonix @pmoetteli Can you confirm that the small fix in d79acf4 fixes your problem?
> 
> This should fix sirius/fwbuilder#3 too.

Sorry for the stupid question: But how do I test that? I probably have to download the source, which includes your fix and then compile it? How do I do that?

Thanks

**Comment by sirius** [comment]
@pmoetteli Of course! Sorry, I'll create binary packages for you to test.

**Comment by sirius** [comment]
Binaries for OSX and Windows: https://github.com/sirius/fwbuilder/releases/tag/v5.3.6-13-gd79acf4

**Comment by ghost** [comment]
Working for me :)

Thanks!

**Comment by pmoetteli** [comment]
Hello,

> Am 23.06.2015 um 17:58 schrieb Steven Coutts notifications@github.com:
> 
> Working for me :)

For me too.

Thanks!

**Comment by sirius** [comment]
Ok, I'll assume this fix works for you too, @bizonix. If not - reopen the issue.
