### ISSUE TITLE
FWBuilder does not start on MAC El Capitan Beta 3

### ISSUE THREAD

**Issue by ghost** [UNINETT/fwbuilder#8]
I know, my fault for running beta, maybe for info more than anything else :)

Process:               fwbuilder [1264]
Path:                  /Applications/fwbuilder.app/Contents/MacOS/fwbuilder
Identifier:            fwbuilder
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           fwbuilder [1264]
User ID:               501

Date/Time:             2015-08-02 10:30:48.361 +0100
OS Version:            Mac OS X 10.11 (15A234d)
Report Version:        11
Anonymous UUID:        A7240D3B-D415-99DC-03CC-8984505BEE89

Sleep/Wake UUID:       199E5DB0-39AF-4449-B2CE-F0AAA6196159

Time Awake Since Boot: 2900 seconds
Time Since Wake:       2600 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/lib/libnetsnmp.25.dylib
  Referenced from: /Applications/fwbuilder.app/Contents/MacOS/fwbuilder
  Reason: image not found

Binary Images:
    0x7fff6c0b5000 -     0x7fff6c0eb937  dyld (360.8) <88677694-40B7-3E21-9612-8585B1F9E98B> /usr/lib/dyld
    0x7fff898f9000 -     0x7fff898f9fff  com.apple.Carbon (154 - 157) <E6AA87EE-3331-34DE-A007-7FE76E5CAB2B> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff96254000 -     0x7fff9627dff7  libxslt.1.dylib (14) <CF5C6F5F-75D6-3C00-B6B2-1032D2799FBC> /usr/lib/libxslt.1.dylib

Model: MacBookPro11,1, BootROM MBP111.0138.B15, 2 processors, Intel Core i5, 2.6 GHz, 8 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.21.87.0.7a1)
Bluetooth: Version 4.4.0d84 16151, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en4
PCI Card: Apple 57762-A0, Ethernet Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Hub
USB Device: Hub
USB Device: Plantronics D100
USB Device: Plantronics C320
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: BUP Slim SL
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2
Thunderbolt Device: Thunderbolt to Gigabit Ethernet Adapter, Apple Inc., 3, 5.5

Tried to symlink missing libnetsnmp library but I can't :(

bash-3.2# sudo ln -s /usr/lib/libnetsnmp.30.dylib /usr/lib/libnetsnmp.25.dylib
ln: /usr/lib/libnetsnmp.25.dylib: Operation not permitted

**Comment by sirius** [comment]
libnetsnmp.30.dylib is supplied with the application in /Applications/fwbuilder.app/Contents/Frameworks/

Can you run "otool -L /Applications/fwbuilder.app/Contents/MacOS/fwbuilder" and paste the output?

**Comment by ghost** [comment]
thyone:~ stevec$ otool -L /Applications/fwbuilder.app/Contents/MacOS/fwbuilder
/Applications/fwbuilder.app/Contents/MacOS/fwbuilder:
    /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
    /usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
    /usr/lib/libnetsnmp.25.dylib (compatibility version 26.0.0, current version 26.0.0)
    /usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
    /usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
    /usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
    @loader_path/../Frameworks/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.7)
    @loader_path/../Frameworks/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.7)
    @loader_path/../Frameworks/QtNetwork.framework/Versions/4/QtNetwork (compatibility version 4.8.0, current version 4.8.7)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
    /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)

**Comment by ghost** [comment]
Works again on latest El Capitan build!
